/*
* generated by Xtext
*/
package org.xtext.example.mydsl.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class MyDslGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ActivityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Activity");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cActivityKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cPeriodiciteKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cPeriodiciteAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cPeriodicitePeriodiciteEnumRuleCall_2_1_0 = (RuleCall)cPeriodiciteAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cActivitesKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cActivitesAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cActivitesActivitesEnumRuleCall_3_1_0 = (RuleCall)cActivitesAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAtelierKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cAtelierAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cAtelierAtelierCrossReference_4_2_0 = (CrossReference)cAtelierAssignment_4_2.eContents().get(0);
		private final RuleCall cAtelierAtelierEStringParserRuleCall_4_2_0_1 = (RuleCall)cAtelierAtelierCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cAtelierAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cAtelierAtelierCrossReference_4_3_1_0 = (CrossReference)cAtelierAssignment_4_3_1.eContents().get(0);
		private final RuleCall cAtelierAtelierEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cAtelierAtelierCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cRes_allocKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cRes_allocAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cRes_allocRes_AllocParserRuleCall_5_2_0 = (RuleCall)cRes_allocAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cRes_allocAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cRes_allocRes_AllocParserRuleCall_5_3_1_0 = (RuleCall)cRes_allocAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cRuleKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cRuleAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cRuleRuleParserRuleCall_6_2_0 = (RuleCall)cRuleAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cRuleAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cRuleRuleParserRuleCall_6_3_1_0 = (RuleCall)cRuleAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cFinKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cFinAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cFinDateParserRuleCall_8_0 = (RuleCall)cFinAssignment_8.eContents().get(0);
		private final Keyword cDebutKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cDebutAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cDebutDateParserRuleCall_10_0 = (RuleCall)cDebutAssignment_10.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//Activity:
		//	"Activity" "{" ("periodicite" periodicite=Periodicite)? ("activites" activites=Activites)? ("atelier" "("
		//	atelier+=[Atelier|EString] ("," atelier+=[Atelier|EString])* ")")? ("res_alloc" "{" res_alloc+=Res_Alloc (","
		//	res_alloc+=Res_Alloc)* "}")? ("rule" "{" rule+=Rule ("," rule+=Rule)* "}")? "fin" fin=Date "debut" debut=Date "}";
		public ParserRule getRule() { return rule; }

		//"Activity" "{" ("periodicite" periodicite=Periodicite)? ("activites" activites=Activites)? ("atelier" "("
		//atelier+=[Atelier|EString] ("," atelier+=[Atelier|EString])* ")")? ("res_alloc" "{" res_alloc+=Res_Alloc (","
		//res_alloc+=Res_Alloc)* "}")? ("rule" "{" rule+=Rule ("," rule+=Rule)* "}")? "fin" fin=Date "debut" debut=Date "}"
		public Group getGroup() { return cGroup; }

		//"Activity"
		public Keyword getActivityKeyword_0() { return cActivityKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//("periodicite" periodicite=Periodicite)?
		public Group getGroup_2() { return cGroup_2; }

		//"periodicite"
		public Keyword getPeriodiciteKeyword_2_0() { return cPeriodiciteKeyword_2_0; }

		//periodicite=Periodicite
		public Assignment getPeriodiciteAssignment_2_1() { return cPeriodiciteAssignment_2_1; }

		//Periodicite
		public RuleCall getPeriodicitePeriodiciteEnumRuleCall_2_1_0() { return cPeriodicitePeriodiciteEnumRuleCall_2_1_0; }

		//("activites" activites=Activites)?
		public Group getGroup_3() { return cGroup_3; }

		//"activites"
		public Keyword getActivitesKeyword_3_0() { return cActivitesKeyword_3_0; }

		//activites=Activites
		public Assignment getActivitesAssignment_3_1() { return cActivitesAssignment_3_1; }

		//Activites
		public RuleCall getActivitesActivitesEnumRuleCall_3_1_0() { return cActivitesActivitesEnumRuleCall_3_1_0; }

		//("atelier" "(" atelier+=[Atelier|EString] ("," atelier+=[Atelier|EString])* ")")?
		public Group getGroup_4() { return cGroup_4; }

		//"atelier"
		public Keyword getAtelierKeyword_4_0() { return cAtelierKeyword_4_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }

		//atelier+=[Atelier|EString]
		public Assignment getAtelierAssignment_4_2() { return cAtelierAssignment_4_2; }

		//[Atelier|EString]
		public CrossReference getAtelierAtelierCrossReference_4_2_0() { return cAtelierAtelierCrossReference_4_2_0; }

		//EString
		public RuleCall getAtelierAtelierEStringParserRuleCall_4_2_0_1() { return cAtelierAtelierEStringParserRuleCall_4_2_0_1; }

		//("," atelier+=[Atelier|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }

		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }

		//atelier+=[Atelier|EString]
		public Assignment getAtelierAssignment_4_3_1() { return cAtelierAssignment_4_3_1; }

		//[Atelier|EString]
		public CrossReference getAtelierAtelierCrossReference_4_3_1_0() { return cAtelierAtelierCrossReference_4_3_1_0; }

		//EString
		public RuleCall getAtelierAtelierEStringParserRuleCall_4_3_1_0_1() { return cAtelierAtelierEStringParserRuleCall_4_3_1_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }

		//("res_alloc" "{" res_alloc+=Res_Alloc ("," res_alloc+=Res_Alloc)* "}")?
		public Group getGroup_5() { return cGroup_5; }

		//"res_alloc"
		public Keyword getRes_allocKeyword_5_0() { return cRes_allocKeyword_5_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }

		//res_alloc+=Res_Alloc
		public Assignment getRes_allocAssignment_5_2() { return cRes_allocAssignment_5_2; }

		//Res_Alloc
		public RuleCall getRes_allocRes_AllocParserRuleCall_5_2_0() { return cRes_allocRes_AllocParserRuleCall_5_2_0; }

		//("," res_alloc+=Res_Alloc)*
		public Group getGroup_5_3() { return cGroup_5_3; }

		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }

		//res_alloc+=Res_Alloc
		public Assignment getRes_allocAssignment_5_3_1() { return cRes_allocAssignment_5_3_1; }

		//Res_Alloc
		public RuleCall getRes_allocRes_AllocParserRuleCall_5_3_1_0() { return cRes_allocRes_AllocParserRuleCall_5_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }

		//("rule" "{" rule+=Rule ("," rule+=Rule)* "}")?
		public Group getGroup_6() { return cGroup_6; }

		//"rule"
		public Keyword getRuleKeyword_6_0() { return cRuleKeyword_6_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }

		//rule+=Rule
		public Assignment getRuleAssignment_6_2() { return cRuleAssignment_6_2; }

		//Rule
		public RuleCall getRuleRuleParserRuleCall_6_2_0() { return cRuleRuleParserRuleCall_6_2_0; }

		//("," rule+=Rule)*
		public Group getGroup_6_3() { return cGroup_6_3; }

		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }

		//rule+=Rule
		public Assignment getRuleAssignment_6_3_1() { return cRuleAssignment_6_3_1; }

		//Rule
		public RuleCall getRuleRuleParserRuleCall_6_3_1_0() { return cRuleRuleParserRuleCall_6_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }

		//"fin"
		public Keyword getFinKeyword_7() { return cFinKeyword_7; }

		//fin=Date
		public Assignment getFinAssignment_8() { return cFinAssignment_8; }

		//Date
		public RuleCall getFinDateParserRuleCall_8_0() { return cFinDateParserRuleCall_8_0; }

		//"debut"
		public Keyword getDebutKeyword_9() { return cDebutKeyword_9; }

		//debut=Date
		public Assignment getDebutAssignment_10() { return cDebutAssignment_10; }

		//Date
		public RuleCall getDebutDateParserRuleCall_10_0() { return cDebutDateParserRuleCall_10_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}

	public class AtelierElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Atelier");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cElevageParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cCultureParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Atelier:
		//	Elevage | Culture;
		public ParserRule getRule() { return rule; }

		//Elevage | Culture
		public Alternatives getAlternatives() { return cAlternatives; }

		//Elevage
		public RuleCall getElevageParserRuleCall_0() { return cElevageParserRuleCall_0; }

		//Culture
		public RuleCall getCultureParserRuleCall_1() { return cCultureParserRuleCall_1; }
	}

	public class Res_AllocElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Res_Alloc");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRes_AllocAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRes_AllocKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDurationKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDurationAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cDurationEIntegerObjectParserRuleCall_3_1_0 = (RuleCall)cDurationAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cRes_typeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cRes_typeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cRes_typeResourceTypeParserRuleCall_4_1_0 = (RuleCall)cRes_typeAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Res_Alloc:
		//	{Res_Alloc} "Res_Alloc" "{" ("duration" duration=EIntegerObject)? ("res_type" res_type=ResourceType)? "}";
		public ParserRule getRule() { return rule; }

		//{Res_Alloc} "Res_Alloc" "{" ("duration" duration=EIntegerObject)? ("res_type" res_type=ResourceType)? "}"
		public Group getGroup() { return cGroup; }

		//{Res_Alloc}
		public Action getRes_AllocAction_0() { return cRes_AllocAction_0; }

		//"Res_Alloc"
		public Keyword getRes_AllocKeyword_1() { return cRes_AllocKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("duration" duration=EIntegerObject)?
		public Group getGroup_3() { return cGroup_3; }

		//"duration"
		public Keyword getDurationKeyword_3_0() { return cDurationKeyword_3_0; }

		//duration=EIntegerObject
		public Assignment getDurationAssignment_3_1() { return cDurationAssignment_3_1; }

		//EIntegerObject
		public RuleCall getDurationEIntegerObjectParserRuleCall_3_1_0() { return cDurationEIntegerObjectParserRuleCall_3_1_0; }

		//("res_type" res_type=ResourceType)?
		public Group getGroup_4() { return cGroup_4; }

		//"res_type"
		public Keyword getRes_typeKeyword_4_0() { return cRes_typeKeyword_4_0; }

		//res_type=ResourceType
		public Assignment getRes_typeAssignment_4_1() { return cRes_typeAssignment_4_1; }

		//ResourceType
		public RuleCall getRes_typeResourceTypeParserRuleCall_4_1_0() { return cRes_typeResourceTypeParserRuleCall_4_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class RuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Rule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRuleAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRuleKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cPredicatKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cPredicatAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final CrossReference cPredicatPredicatCrossReference_3_2_0 = (CrossReference)cPredicatAssignment_3_2.eContents().get(0);
		private final RuleCall cPredicatPredicatEStringParserRuleCall_3_2_0_1 = (RuleCall)cPredicatPredicatCrossReference_3_2_0.eContents().get(1);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cPredicatAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final CrossReference cPredicatPredicatCrossReference_3_3_1_0 = (CrossReference)cPredicatAssignment_3_3_1.eContents().get(0);
		private final RuleCall cPredicatPredicatEStringParserRuleCall_3_3_1_0_1 = (RuleCall)cPredicatPredicatCrossReference_3_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Rule:
		//	{Rule} "Rule" "{" ("predicat" "(" predicat+=[Predicat|EString] ("," predicat+=[Predicat|EString])* ")")? "}";
		public ParserRule getRule() { return rule; }

		//{Rule} "Rule" "{" ("predicat" "(" predicat+=[Predicat|EString] ("," predicat+=[Predicat|EString])* ")")? "}"
		public Group getGroup() { return cGroup; }

		//{Rule}
		public Action getRuleAction_0() { return cRuleAction_0; }

		//"Rule"
		public Keyword getRuleKeyword_1() { return cRuleKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("predicat" "(" predicat+=[Predicat|EString] ("," predicat+=[Predicat|EString])* ")")?
		public Group getGroup_3() { return cGroup_3; }

		//"predicat"
		public Keyword getPredicatKeyword_3_0() { return cPredicatKeyword_3_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_3_1() { return cLeftParenthesisKeyword_3_1; }

		//predicat+=[Predicat|EString]
		public Assignment getPredicatAssignment_3_2() { return cPredicatAssignment_3_2; }

		//[Predicat|EString]
		public CrossReference getPredicatPredicatCrossReference_3_2_0() { return cPredicatPredicatCrossReference_3_2_0; }

		//EString
		public RuleCall getPredicatPredicatEStringParserRuleCall_3_2_0_1() { return cPredicatPredicatEStringParserRuleCall_3_2_0_1; }

		//("," predicat+=[Predicat|EString])*
		public Group getGroup_3_3() { return cGroup_3_3; }

		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }

		//predicat+=[Predicat|EString]
		public Assignment getPredicatAssignment_3_3_1() { return cPredicatAssignment_3_3_1; }

		//[Predicat|EString]
		public CrossReference getPredicatPredicatCrossReference_3_3_1_0() { return cPredicatPredicatCrossReference_3_3_1_0; }

		//EString
		public RuleCall getPredicatPredicatEStringParserRuleCall_3_3_1_0_1() { return cPredicatPredicatEStringParserRuleCall_3_3_1_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_3_4() { return cRightParenthesisKeyword_3_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class DateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Date");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cDateAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cDateKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDayKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDayAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cDayEIntegerObjectParserRuleCall_3_1_0 = (RuleCall)cDayAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cMonthKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cMonthAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cMonthMonthEnumRuleCall_4_1_0 = (RuleCall)cMonthAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Date:
		//	{Date} "Date" "{" ("day" day=EIntegerObject)? ("month" month=Month)? "}";
		public ParserRule getRule() { return rule; }

		//{Date} "Date" "{" ("day" day=EIntegerObject)? ("month" month=Month)? "}"
		public Group getGroup() { return cGroup; }

		//{Date}
		public Action getDateAction_0() { return cDateAction_0; }

		//"Date"
		public Keyword getDateKeyword_1() { return cDateKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("day" day=EIntegerObject)?
		public Group getGroup_3() { return cGroup_3; }

		//"day"
		public Keyword getDayKeyword_3_0() { return cDayKeyword_3_0; }

		//day=EIntegerObject
		public Assignment getDayAssignment_3_1() { return cDayAssignment_3_1; }

		//EIntegerObject
		public RuleCall getDayEIntegerObjectParserRuleCall_3_1_0() { return cDayEIntegerObjectParserRuleCall_3_1_0; }

		//("month" month=Month)?
		public Group getGroup_4() { return cGroup_4; }

		//"month"
		public Keyword getMonthKeyword_4_0() { return cMonthKeyword_4_0; }

		//month=Month
		public Assignment getMonthAssignment_4_1() { return cMonthAssignment_4_1; }

		//Month
		public RuleCall getMonthMonthEnumRuleCall_4_1_0() { return cMonthMonthEnumRuleCall_4_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class EIntegerObjectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EIntegerObject");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EIntegerObject returns ecore::EIntegerObject:
		//	"-"? INT;
		public ParserRule getRule() { return rule; }

		//"-"? INT
		public Group getGroup() { return cGroup; }

		//"-"?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}

	public class ResourceTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ResourceType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cResourceTypeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cResourceTypeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cResourceKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cResourceAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cResourceRessourceCrossReference_4_1_0 = (CrossReference)cResourceAssignment_4_1.eContents().get(0);
		private final RuleCall cResourceRessourceEStringParserRuleCall_4_1_0_1 = (RuleCall)cResourceRessourceCrossReference_4_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//ResourceType:
		//	{ResourceType} "ResourceType" name=EString "{" ("resource" resource=[Ressource|EString])? "}";
		public ParserRule getRule() { return rule; }

		//{ResourceType} "ResourceType" name=EString "{" ("resource" resource=[Ressource|EString])? "}"
		public Group getGroup() { return cGroup; }

		//{ResourceType}
		public Action getResourceTypeAction_0() { return cResourceTypeAction_0; }

		//"ResourceType"
		public Keyword getResourceTypeKeyword_1() { return cResourceTypeKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("resource" resource=[Ressource|EString])?
		public Group getGroup_4() { return cGroup_4; }

		//"resource"
		public Keyword getResourceKeyword_4_0() { return cResourceKeyword_4_0; }

		//resource=[Ressource|EString]
		public Assignment getResourceAssignment_4_1() { return cResourceAssignment_4_1; }

		//[Ressource|EString]
		public CrossReference getResourceRessourceCrossReference_4_1_0() { return cResourceRessourceCrossReference_4_1_0; }

		//EString
		public RuleCall getResourceRessourceEStringParserRuleCall_4_1_0_1() { return cResourceRessourceEStringParserRuleCall_4_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//	STRING | ID;
		public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}

	public class RessourceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Ressource");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRessourceAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRessourceKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cResourceTypeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cResourceTypeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cResourceTypeResourceTypeCrossReference_4_1_0 = (CrossReference)cResourceTypeAssignment_4_1.eContents().get(0);
		private final RuleCall cResourceTypeResourceTypeEStringParserRuleCall_4_1_0_1 = (RuleCall)cResourceTypeResourceTypeCrossReference_4_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Ressource:
		//	{Ressource} "Ressource" name=EString "{" ("resourceType" resourceType=[ResourceType|EString])? "}";
		public ParserRule getRule() { return rule; }

		//{Ressource} "Ressource" name=EString "{" ("resourceType" resourceType=[ResourceType|EString])? "}"
		public Group getGroup() { return cGroup; }

		//{Ressource}
		public Action getRessourceAction_0() { return cRessourceAction_0; }

		//"Ressource"
		public Keyword getRessourceKeyword_1() { return cRessourceKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("resourceType" resourceType=[ResourceType|EString])?
		public Group getGroup_4() { return cGroup_4; }

		//"resourceType"
		public Keyword getResourceTypeKeyword_4_0() { return cResourceTypeKeyword_4_0; }

		//resourceType=[ResourceType|EString]
		public Assignment getResourceTypeAssignment_4_1() { return cResourceTypeAssignment_4_1; }

		//[ResourceType|EString]
		public CrossReference getResourceTypeResourceTypeCrossReference_4_1_0() { return cResourceTypeResourceTypeCrossReference_4_1_0; }

		//EString
		public RuleCall getResourceTypeResourceTypeEStringParserRuleCall_4_1_0_1() { return cResourceTypeResourceTypeEStringParserRuleCall_4_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class PredicatElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Predicat");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPredicatAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPredicatKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Predicat:
		//	{Predicat} "Predicat";
		public ParserRule getRule() { return rule; }

		//{Predicat} "Predicat"
		public Group getGroup() { return cGroup; }

		//{Predicat}
		public Action getPredicatAction_0() { return cPredicatAction_0; }

		//"Predicat"
		public Keyword getPredicatKeyword_1() { return cPredicatKeyword_1; }
	}

	public class ElevageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Elevage");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cElevageAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cElevageKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cAnimalsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cAnimalsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cAnimalsAnimalsEnumRuleCall_3_1_0 = (RuleCall)cAnimalsAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cActivityKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cActivityAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cActivityActivityCrossReference_4_1_0 = (CrossReference)cActivityAssignment_4_1.eContents().get(0);
		private final RuleCall cActivityActivityEStringParserRuleCall_4_1_0_1 = (RuleCall)cActivityActivityCrossReference_4_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Elevage:
		//	{Elevage} "Elevage" "{" ("animals" animals=Animals)? ("activity" activity=[Activity|EString])? "}";
		public ParserRule getRule() { return rule; }

		//{Elevage} "Elevage" "{" ("animals" animals=Animals)? ("activity" activity=[Activity|EString])? "}"
		public Group getGroup() { return cGroup; }

		//{Elevage}
		public Action getElevageAction_0() { return cElevageAction_0; }

		//"Elevage"
		public Keyword getElevageKeyword_1() { return cElevageKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("animals" animals=Animals)?
		public Group getGroup_3() { return cGroup_3; }

		//"animals"
		public Keyword getAnimalsKeyword_3_0() { return cAnimalsKeyword_3_0; }

		//animals=Animals
		public Assignment getAnimalsAssignment_3_1() { return cAnimalsAssignment_3_1; }

		//Animals
		public RuleCall getAnimalsAnimalsEnumRuleCall_3_1_0() { return cAnimalsAnimalsEnumRuleCall_3_1_0; }

		//("activity" activity=[Activity|EString])?
		public Group getGroup_4() { return cGroup_4; }

		//"activity"
		public Keyword getActivityKeyword_4_0() { return cActivityKeyword_4_0; }

		//activity=[Activity|EString]
		public Assignment getActivityAssignment_4_1() { return cActivityAssignment_4_1; }

		//[Activity|EString]
		public CrossReference getActivityActivityCrossReference_4_1_0() { return cActivityActivityCrossReference_4_1_0; }

		//EString
		public RuleCall getActivityActivityEStringParserRuleCall_4_1_0_1() { return cActivityActivityEStringParserRuleCall_4_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class CultureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Culture");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCultureAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cCultureKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCerealsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cCerealsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cCerealsCerealEnumRuleCall_3_1_0 = (RuleCall)cCerealsAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cActivityKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cActivityAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cActivityActivityCrossReference_4_1_0 = (CrossReference)cActivityAssignment_4_1.eContents().get(0);
		private final RuleCall cActivityActivityEStringParserRuleCall_4_1_0_1 = (RuleCall)cActivityActivityCrossReference_4_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Culture:
		//	{Culture} "Culture" "{" ("cereals" cereals=Cereal)? ("activity" activity=[Activity|EString])? "}";
		public ParserRule getRule() { return rule; }

		//{Culture} "Culture" "{" ("cereals" cereals=Cereal)? ("activity" activity=[Activity|EString])? "}"
		public Group getGroup() { return cGroup; }

		//{Culture}
		public Action getCultureAction_0() { return cCultureAction_0; }

		//"Culture"
		public Keyword getCultureKeyword_1() { return cCultureKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("cereals" cereals=Cereal)?
		public Group getGroup_3() { return cGroup_3; }

		//"cereals"
		public Keyword getCerealsKeyword_3_0() { return cCerealsKeyword_3_0; }

		//cereals=Cereal
		public Assignment getCerealsAssignment_3_1() { return cCerealsAssignment_3_1; }

		//Cereal
		public RuleCall getCerealsCerealEnumRuleCall_3_1_0() { return cCerealsCerealEnumRuleCall_3_1_0; }

		//("activity" activity=[Activity|EString])?
		public Group getGroup_4() { return cGroup_4; }

		//"activity"
		public Keyword getActivityKeyword_4_0() { return cActivityKeyword_4_0; }

		//activity=[Activity|EString]
		public Assignment getActivityAssignment_4_1() { return cActivityAssignment_4_1; }

		//[Activity|EString]
		public CrossReference getActivityActivityCrossReference_4_1_0() { return cActivityActivityCrossReference_4_1_0; }

		//EString
		public RuleCall getActivityActivityEStringParserRuleCall_4_1_0_1() { return cActivityActivityEStringParserRuleCall_4_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	
	
	public class PeriodiciteElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "Periodicite");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cHALF_DAILYEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cHALF_DAILYHALF_DAILYKeyword_0_0 = (Keyword)cHALF_DAILYEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cDAILYEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cDAILYDAILYKeyword_1_0 = (Keyword)cDAILYEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cWEEKLYEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cWEEKLYWEEKLYKeyword_2_0 = (Keyword)cWEEKLYEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cMONTHLYEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cMONTHLYMONTHLYKeyword_3_0 = (Keyword)cMONTHLYEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum Periodicite:
		//	HALF_DAILY | DAILY | WEEKLY | MONTHLY;
		public EnumRule getRule() { return rule; }

		//HALF_DAILY | DAILY | WEEKLY | MONTHLY
		public Alternatives getAlternatives() { return cAlternatives; }

		//HALF_DAILY
		public EnumLiteralDeclaration getHALF_DAILYEnumLiteralDeclaration_0() { return cHALF_DAILYEnumLiteralDeclaration_0; }

		//"HALF_DAILY"
		public Keyword getHALF_DAILYHALF_DAILYKeyword_0_0() { return cHALF_DAILYHALF_DAILYKeyword_0_0; }

		//DAILY
		public EnumLiteralDeclaration getDAILYEnumLiteralDeclaration_1() { return cDAILYEnumLiteralDeclaration_1; }

		//"DAILY"
		public Keyword getDAILYDAILYKeyword_1_0() { return cDAILYDAILYKeyword_1_0; }

		//WEEKLY
		public EnumLiteralDeclaration getWEEKLYEnumLiteralDeclaration_2() { return cWEEKLYEnumLiteralDeclaration_2; }

		//"WEEKLY"
		public Keyword getWEEKLYWEEKLYKeyword_2_0() { return cWEEKLYWEEKLYKeyword_2_0; }

		//MONTHLY
		public EnumLiteralDeclaration getMONTHLYEnumLiteralDeclaration_3() { return cMONTHLYEnumLiteralDeclaration_3; }

		//"MONTHLY"
		public Keyword getMONTHLYMONTHLYKeyword_3_0() { return cMONTHLYMONTHLYKeyword_3_0; }
	}

	public class ActivitesElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "Activites");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cLABOUREnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cLABOURLABOURKeyword_0_0 = (Keyword)cLABOUREnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cSEMISEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cSEMISSEMISKeyword_1_0 = (Keyword)cSEMISEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cIRRIGATIONEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cIRRIGATIONIRRIGATIONKeyword_2_0 = (Keyword)cIRRIGATIONEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cFERTILISATIONEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cFERTILISATIONFERTILISATIONKeyword_3_0 = (Keyword)cFERTILISATIONEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cRECOLTEEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cRECOLTERECOLTEKeyword_4_0 = (Keyword)cRECOLTEEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cALIMENTATIONEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cALIMENTATIONALIMENTATIONKeyword_5_0 = (Keyword)cALIMENTATIONEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cTRAITEEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cTRAITETRAITEKeyword_6_0 = (Keyword)cTRAITEEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cSURVEILLANCE_AGNELAGEEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cSURVEILLANCE_AGNELAGESURVEILLANCE_AGNELAGEKeyword_7_0 = (Keyword)cSURVEILLANCE_AGNELAGEEnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cSURVEILLANCE_VELAGEEnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cSURVEILLANCE_VELAGESURVEILLANCE_VELAGEKeyword_8_0 = (Keyword)cSURVEILLANCE_VELAGEEnumLiteralDeclaration_8.eContents().get(0);
		
		//enum Activites:
		//	LABOUR | SEMIS | IRRIGATION | FERTILISATION | RECOLTE | ALIMENTATION | TRAITE | SURVEILLANCE_AGNELAGE |
		//	SURVEILLANCE_VELAGE;
		public EnumRule getRule() { return rule; }

		//LABOUR | SEMIS | IRRIGATION | FERTILISATION | RECOLTE | ALIMENTATION | TRAITE | SURVEILLANCE_AGNELAGE |
		//SURVEILLANCE_VELAGE
		public Alternatives getAlternatives() { return cAlternatives; }

		//LABOUR
		public EnumLiteralDeclaration getLABOUREnumLiteralDeclaration_0() { return cLABOUREnumLiteralDeclaration_0; }

		//"LABOUR"
		public Keyword getLABOURLABOURKeyword_0_0() { return cLABOURLABOURKeyword_0_0; }

		//SEMIS
		public EnumLiteralDeclaration getSEMISEnumLiteralDeclaration_1() { return cSEMISEnumLiteralDeclaration_1; }

		//"SEMIS"
		public Keyword getSEMISSEMISKeyword_1_0() { return cSEMISSEMISKeyword_1_0; }

		//IRRIGATION
		public EnumLiteralDeclaration getIRRIGATIONEnumLiteralDeclaration_2() { return cIRRIGATIONEnumLiteralDeclaration_2; }

		//"IRRIGATION"
		public Keyword getIRRIGATIONIRRIGATIONKeyword_2_0() { return cIRRIGATIONIRRIGATIONKeyword_2_0; }

		//FERTILISATION
		public EnumLiteralDeclaration getFERTILISATIONEnumLiteralDeclaration_3() { return cFERTILISATIONEnumLiteralDeclaration_3; }

		//"FERTILISATION"
		public Keyword getFERTILISATIONFERTILISATIONKeyword_3_0() { return cFERTILISATIONFERTILISATIONKeyword_3_0; }

		//RECOLTE
		public EnumLiteralDeclaration getRECOLTEEnumLiteralDeclaration_4() { return cRECOLTEEnumLiteralDeclaration_4; }

		//"RECOLTE"
		public Keyword getRECOLTERECOLTEKeyword_4_0() { return cRECOLTERECOLTEKeyword_4_0; }

		//ALIMENTATION
		public EnumLiteralDeclaration getALIMENTATIONEnumLiteralDeclaration_5() { return cALIMENTATIONEnumLiteralDeclaration_5; }

		//"ALIMENTATION"
		public Keyword getALIMENTATIONALIMENTATIONKeyword_5_0() { return cALIMENTATIONALIMENTATIONKeyword_5_0; }

		//TRAITE
		public EnumLiteralDeclaration getTRAITEEnumLiteralDeclaration_6() { return cTRAITEEnumLiteralDeclaration_6; }

		//"TRAITE"
		public Keyword getTRAITETRAITEKeyword_6_0() { return cTRAITETRAITEKeyword_6_0; }

		//SURVEILLANCE_AGNELAGE
		public EnumLiteralDeclaration getSURVEILLANCE_AGNELAGEEnumLiteralDeclaration_7() { return cSURVEILLANCE_AGNELAGEEnumLiteralDeclaration_7; }

		//"SURVEILLANCE_AGNELAGE"
		public Keyword getSURVEILLANCE_AGNELAGESURVEILLANCE_AGNELAGEKeyword_7_0() { return cSURVEILLANCE_AGNELAGESURVEILLANCE_AGNELAGEKeyword_7_0; }

		//SURVEILLANCE_VELAGE
		public EnumLiteralDeclaration getSURVEILLANCE_VELAGEEnumLiteralDeclaration_8() { return cSURVEILLANCE_VELAGEEnumLiteralDeclaration_8; }

		//"SURVEILLANCE_VELAGE"
		public Keyword getSURVEILLANCE_VELAGESURVEILLANCE_VELAGEKeyword_8_0() { return cSURVEILLANCE_VELAGESURVEILLANCE_VELAGEKeyword_8_0; }
	}

	public class MonthElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "Month");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cJANUARYEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cJANUARYJANUARYKeyword_0_0 = (Keyword)cJANUARYEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cFEBRARYEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cFEBRARYFEBRARYKeyword_1_0 = (Keyword)cFEBRARYEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cMARCHEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cMARCHMARCHKeyword_2_0 = (Keyword)cMARCHEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cAPRILEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cAPRILAPRILKeyword_3_0 = (Keyword)cAPRILEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cMAYEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cMAYMAYKeyword_4_0 = (Keyword)cMAYEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cJUNEEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cJUNEJUNEKeyword_5_0 = (Keyword)cJUNEEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cJULYEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cJULYJULYKeyword_6_0 = (Keyword)cJULYEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cAUGUSTEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cAUGUSTAUGUSTKeyword_7_0 = (Keyword)cAUGUSTEnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cSEPTEMBEREnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cSEPTEMBERSEPTEMBERKeyword_8_0 = (Keyword)cSEPTEMBEREnumLiteralDeclaration_8.eContents().get(0);
		private final EnumLiteralDeclaration cOCTOBEREnumLiteralDeclaration_9 = (EnumLiteralDeclaration)cAlternatives.eContents().get(9);
		private final Keyword cOCTOBEROCTOBERKeyword_9_0 = (Keyword)cOCTOBEREnumLiteralDeclaration_9.eContents().get(0);
		private final EnumLiteralDeclaration cNOVEMBEREnumLiteralDeclaration_10 = (EnumLiteralDeclaration)cAlternatives.eContents().get(10);
		private final Keyword cNOVEMBERNOVEMBERKeyword_10_0 = (Keyword)cNOVEMBEREnumLiteralDeclaration_10.eContents().get(0);
		private final EnumLiteralDeclaration cDECEMBEREnumLiteralDeclaration_11 = (EnumLiteralDeclaration)cAlternatives.eContents().get(11);
		private final Keyword cDECEMBERDECEMBERKeyword_11_0 = (Keyword)cDECEMBEREnumLiteralDeclaration_11.eContents().get(0);
		
		//enum Month:
		//	JANUARY | FEBRARY | MARCH | APRIL | MAY | JUNE | JULY | AUGUST | SEPTEMBER | OCTOBER | NOVEMBER | DECEMBER;
		public EnumRule getRule() { return rule; }

		//JANUARY | FEBRARY | MARCH | APRIL | MAY | JUNE | JULY | AUGUST | SEPTEMBER | OCTOBER | NOVEMBER | DECEMBER
		public Alternatives getAlternatives() { return cAlternatives; }

		//JANUARY
		public EnumLiteralDeclaration getJANUARYEnumLiteralDeclaration_0() { return cJANUARYEnumLiteralDeclaration_0; }

		//"JANUARY"
		public Keyword getJANUARYJANUARYKeyword_0_0() { return cJANUARYJANUARYKeyword_0_0; }

		//FEBRARY
		public EnumLiteralDeclaration getFEBRARYEnumLiteralDeclaration_1() { return cFEBRARYEnumLiteralDeclaration_1; }

		//"FEBRARY"
		public Keyword getFEBRARYFEBRARYKeyword_1_0() { return cFEBRARYFEBRARYKeyword_1_0; }

		//MARCH
		public EnumLiteralDeclaration getMARCHEnumLiteralDeclaration_2() { return cMARCHEnumLiteralDeclaration_2; }

		//"MARCH"
		public Keyword getMARCHMARCHKeyword_2_0() { return cMARCHMARCHKeyword_2_0; }

		//APRIL
		public EnumLiteralDeclaration getAPRILEnumLiteralDeclaration_3() { return cAPRILEnumLiteralDeclaration_3; }

		//"APRIL"
		public Keyword getAPRILAPRILKeyword_3_0() { return cAPRILAPRILKeyword_3_0; }

		//MAY
		public EnumLiteralDeclaration getMAYEnumLiteralDeclaration_4() { return cMAYEnumLiteralDeclaration_4; }

		//"MAY"
		public Keyword getMAYMAYKeyword_4_0() { return cMAYMAYKeyword_4_0; }

		//JUNE
		public EnumLiteralDeclaration getJUNEEnumLiteralDeclaration_5() { return cJUNEEnumLiteralDeclaration_5; }

		//"JUNE"
		public Keyword getJUNEJUNEKeyword_5_0() { return cJUNEJUNEKeyword_5_0; }

		//JULY
		public EnumLiteralDeclaration getJULYEnumLiteralDeclaration_6() { return cJULYEnumLiteralDeclaration_6; }

		//"JULY"
		public Keyword getJULYJULYKeyword_6_0() { return cJULYJULYKeyword_6_0; }

		//AUGUST
		public EnumLiteralDeclaration getAUGUSTEnumLiteralDeclaration_7() { return cAUGUSTEnumLiteralDeclaration_7; }

		//"AUGUST"
		public Keyword getAUGUSTAUGUSTKeyword_7_0() { return cAUGUSTAUGUSTKeyword_7_0; }

		//SEPTEMBER
		public EnumLiteralDeclaration getSEPTEMBEREnumLiteralDeclaration_8() { return cSEPTEMBEREnumLiteralDeclaration_8; }

		//"SEPTEMBER"
		public Keyword getSEPTEMBERSEPTEMBERKeyword_8_0() { return cSEPTEMBERSEPTEMBERKeyword_8_0; }

		//OCTOBER
		public EnumLiteralDeclaration getOCTOBEREnumLiteralDeclaration_9() { return cOCTOBEREnumLiteralDeclaration_9; }

		//"OCTOBER"
		public Keyword getOCTOBEROCTOBERKeyword_9_0() { return cOCTOBEROCTOBERKeyword_9_0; }

		//NOVEMBER
		public EnumLiteralDeclaration getNOVEMBEREnumLiteralDeclaration_10() { return cNOVEMBEREnumLiteralDeclaration_10; }

		//"NOVEMBER"
		public Keyword getNOVEMBERNOVEMBERKeyword_10_0() { return cNOVEMBERNOVEMBERKeyword_10_0; }

		//DECEMBER
		public EnumLiteralDeclaration getDECEMBEREnumLiteralDeclaration_11() { return cDECEMBEREnumLiteralDeclaration_11; }

		//"DECEMBER"
		public Keyword getDECEMBERDECEMBERKeyword_11_0() { return cDECEMBERDECEMBERKeyword_11_0; }
	}

	public class AnimalsElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "Animals");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cOVINEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cOVINOVINKeyword_0_0 = (Keyword)cOVINEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cBOVINEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cBOVINBOVINKeyword_1_0 = (Keyword)cBOVINEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum Animals:
		//	OVIN | BOVIN;
		public EnumRule getRule() { return rule; }

		//OVIN | BOVIN
		public Alternatives getAlternatives() { return cAlternatives; }

		//OVIN
		public EnumLiteralDeclaration getOVINEnumLiteralDeclaration_0() { return cOVINEnumLiteralDeclaration_0; }

		//"OVIN"
		public Keyword getOVINOVINKeyword_0_0() { return cOVINOVINKeyword_0_0; }

		//BOVIN
		public EnumLiteralDeclaration getBOVINEnumLiteralDeclaration_1() { return cBOVINEnumLiteralDeclaration_1; }

		//"BOVIN"
		public Keyword getBOVINBOVINKeyword_1_0() { return cBOVINBOVINKeyword_1_0; }
	}

	public class CerealElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "Cereal");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cCORNEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cCORNCORNKeyword_0_0 = (Keyword)cCORNEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cWHEATEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cWHEATWHEATKeyword_1_0 = (Keyword)cWHEATEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cSORGHUMEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cSORGHUMSORGHUMKeyword_2_0 = (Keyword)cSORGHUMEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum Cereal:
		//	CORN | WHEAT | SORGHUM;
		public EnumRule getRule() { return rule; }

		//CORN | WHEAT | SORGHUM
		public Alternatives getAlternatives() { return cAlternatives; }

		//CORN
		public EnumLiteralDeclaration getCORNEnumLiteralDeclaration_0() { return cCORNEnumLiteralDeclaration_0; }

		//"CORN"
		public Keyword getCORNCORNKeyword_0_0() { return cCORNCORNKeyword_0_0; }

		//WHEAT
		public EnumLiteralDeclaration getWHEATEnumLiteralDeclaration_1() { return cWHEATEnumLiteralDeclaration_1; }

		//"WHEAT"
		public Keyword getWHEATWHEATKeyword_1_0() { return cWHEATWHEATKeyword_1_0; }

		//SORGHUM
		public EnumLiteralDeclaration getSORGHUMEnumLiteralDeclaration_2() { return cSORGHUMEnumLiteralDeclaration_2; }

		//"SORGHUM"
		public Keyword getSORGHUMSORGHUMKeyword_2_0() { return cSORGHUMSORGHUMKeyword_2_0; }
	}
	
	private final ActivityElements pActivity;
	private final AtelierElements pAtelier;
	private final PeriodiciteElements unknownRulePeriodicite;
	private final Res_AllocElements pRes_Alloc;
	private final RuleElements pRule;
	private final DateElements pDate;
	private final ActivitesElements unknownRuleActivites;
	private final EIntegerObjectElements pEIntegerObject;
	private final ResourceTypeElements pResourceType;
	private final EStringElements pEString;
	private final RessourceElements pRessource;
	private final PredicatElements pPredicat;
	private final MonthElements unknownRuleMonth;
	private final ElevageElements pElevage;
	private final CultureElements pCulture;
	private final AnimalsElements unknownRuleAnimals;
	private final CerealElements unknownRuleCereal;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pActivity = new ActivityElements();
		this.pAtelier = new AtelierElements();
		this.unknownRulePeriodicite = new PeriodiciteElements();
		this.pRes_Alloc = new Res_AllocElements();
		this.pRule = new RuleElements();
		this.pDate = new DateElements();
		this.unknownRuleActivites = new ActivitesElements();
		this.pEIntegerObject = new EIntegerObjectElements();
		this.pResourceType = new ResourceTypeElements();
		this.pEString = new EStringElements();
		this.pRessource = new RessourceElements();
		this.pPredicat = new PredicatElements();
		this.unknownRuleMonth = new MonthElements();
		this.pElevage = new ElevageElements();
		this.pCulture = new CultureElements();
		this.unknownRuleAnimals = new AnimalsElements();
		this.unknownRuleCereal = new CerealElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Activity:
	//	"Activity" "{" ("periodicite" periodicite=Periodicite)? ("activites" activites=Activites)? ("atelier" "("
	//	atelier+=[Atelier|EString] ("," atelier+=[Atelier|EString])* ")")? ("res_alloc" "{" res_alloc+=Res_Alloc (","
	//	res_alloc+=Res_Alloc)* "}")? ("rule" "{" rule+=Rule ("," rule+=Rule)* "}")? "fin" fin=Date "debut" debut=Date "}";
	public ActivityElements getActivityAccess() {
		return pActivity;
	}
	
	public ParserRule getActivityRule() {
		return getActivityAccess().getRule();
	}

	//Atelier:
	//	Elevage | Culture;
	public AtelierElements getAtelierAccess() {
		return pAtelier;
	}
	
	public ParserRule getAtelierRule() {
		return getAtelierAccess().getRule();
	}

	//enum Periodicite:
	//	HALF_DAILY | DAILY | WEEKLY | MONTHLY;
	public PeriodiciteElements getPeriodiciteAccess() {
		return unknownRulePeriodicite;
	}
	
	public EnumRule getPeriodiciteRule() {
		return getPeriodiciteAccess().getRule();
	}

	//Res_Alloc:
	//	{Res_Alloc} "Res_Alloc" "{" ("duration" duration=EIntegerObject)? ("res_type" res_type=ResourceType)? "}";
	public Res_AllocElements getRes_AllocAccess() {
		return pRes_Alloc;
	}
	
	public ParserRule getRes_AllocRule() {
		return getRes_AllocAccess().getRule();
	}

	//Rule:
	//	{Rule} "Rule" "{" ("predicat" "(" predicat+=[Predicat|EString] ("," predicat+=[Predicat|EString])* ")")? "}";
	public RuleElements getRuleAccess() {
		return pRule;
	}
	
	public ParserRule getRuleRule() {
		return getRuleAccess().getRule();
	}

	//Date:
	//	{Date} "Date" "{" ("day" day=EIntegerObject)? ("month" month=Month)? "}";
	public DateElements getDateAccess() {
		return pDate;
	}
	
	public ParserRule getDateRule() {
		return getDateAccess().getRule();
	}

	//enum Activites:
	//	LABOUR | SEMIS | IRRIGATION | FERTILISATION | RECOLTE | ALIMENTATION | TRAITE | SURVEILLANCE_AGNELAGE |
	//	SURVEILLANCE_VELAGE;
	public ActivitesElements getActivitesAccess() {
		return unknownRuleActivites;
	}
	
	public EnumRule getActivitesRule() {
		return getActivitesAccess().getRule();
	}

	//EIntegerObject returns ecore::EIntegerObject:
	//	"-"? INT;
	public EIntegerObjectElements getEIntegerObjectAccess() {
		return pEIntegerObject;
	}
	
	public ParserRule getEIntegerObjectRule() {
		return getEIntegerObjectAccess().getRule();
	}

	//ResourceType:
	//	{ResourceType} "ResourceType" name=EString "{" ("resource" resource=[Ressource|EString])? "}";
	public ResourceTypeElements getResourceTypeAccess() {
		return pResourceType;
	}
	
	public ParserRule getResourceTypeRule() {
		return getResourceTypeAccess().getRule();
	}

	//EString returns ecore::EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//Ressource:
	//	{Ressource} "Ressource" name=EString "{" ("resourceType" resourceType=[ResourceType|EString])? "}";
	public RessourceElements getRessourceAccess() {
		return pRessource;
	}
	
	public ParserRule getRessourceRule() {
		return getRessourceAccess().getRule();
	}

	//Predicat:
	//	{Predicat} "Predicat";
	public PredicatElements getPredicatAccess() {
		return pPredicat;
	}
	
	public ParserRule getPredicatRule() {
		return getPredicatAccess().getRule();
	}

	//enum Month:
	//	JANUARY | FEBRARY | MARCH | APRIL | MAY | JUNE | JULY | AUGUST | SEPTEMBER | OCTOBER | NOVEMBER | DECEMBER;
	public MonthElements getMonthAccess() {
		return unknownRuleMonth;
	}
	
	public EnumRule getMonthRule() {
		return getMonthAccess().getRule();
	}

	//Elevage:
	//	{Elevage} "Elevage" "{" ("animals" animals=Animals)? ("activity" activity=[Activity|EString])? "}";
	public ElevageElements getElevageAccess() {
		return pElevage;
	}
	
	public ParserRule getElevageRule() {
		return getElevageAccess().getRule();
	}

	//Culture:
	//	{Culture} "Culture" "{" ("cereals" cereals=Cereal)? ("activity" activity=[Activity|EString])? "}";
	public CultureElements getCultureAccess() {
		return pCulture;
	}
	
	public ParserRule getCultureRule() {
		return getCultureAccess().getRule();
	}

	//enum Animals:
	//	OVIN | BOVIN;
	public AnimalsElements getAnimalsAccess() {
		return unknownRuleAnimals;
	}
	
	public EnumRule getAnimalsRule() {
		return getAnimalsAccess().getRule();
	}

	//enum Cereal:
	//	CORN | WHEAT | SORGHUM;
	public CerealElements getCerealAccess() {
		return unknownRuleCereal;
	}
	
	public EnumRule getCerealRule() {
		return getCerealAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
